const {chromium}=require(process.env.PLAYWRIGHT_MODULE || '/home/ana/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');
(async()=>{
 const b=await chromium.launch({executablePath:'/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']});
 const p=await b.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(15000);
 const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:18321');
 await p.getByRole('button',{name:'Create your first project'}).click();
 await p.getByPlaceholder('e.g. 4p form factor study').fill('E6 browser run audit');
 await p.locator('.modal select').selectOption('e6');
 await p.getByRole('button',{name:'Create',exact:true}).click();
 await p.getByRole('heading',{name:'Materials — alphabet building blocks',exact:true}).waitFor();
 await p.getByRole('link',{name:'Flows',exact:true}).click();
 await p.getByRole('heading',{name:'E6 · extend & sew chain (smoke)',exact:true}).click();
 await p.getByRole('button',{name:'Compile',exact:true}).click();
 await p.getByRole('button',{name:'▶ Run this plan',exact:true}).click();
 await p.waitForURL('**/runs/*');
 await p.locator('h1 .status-done').waitFor({timeout:90000});
 const rid=new URL(p.url()).pathname.split('/').pop();
 const run=await (await p.request.get('http://127.0.0.1:18321/api/runs/'+rid)).json();
 await p.screenshot({path:path.join(__dirname,'successful-run.png'),fullPage:true});
 await p.getByRole('link',{name:'Results',exact:true}).click();
 await p.getByRole('button',{name:'Inspect',exact:true}).first().waitFor();
 const result={status:run.status,nSteps:run.steps.length,allStepsDone:run.steps.every(s=>['done','skipped'].includes(s.status)),renderErrors:errors,resultRows:await p.locator('tbody tr').count()};
 await p.getByRole('button',{name:'Inspect',exact:true}).first().click();
 await p.waitForTimeout(1500);
 result.inspectorText=(await p.locator('body').innerText()).slice(-500);
 fs.writeFileSync(path.join(__dirname,'browser-run-results.json'),JSON.stringify(result,null,2));console.log(result);
 await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
